services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flip
      POSTGRES_USER: flip
      POSTGRES_PASSWORD: flip
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flip -d flip"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: anguy491/v1:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flip
      SPRING_DATASOURCE_USERNAME: flip
      SPRING_DATASOURCE_PASSWORD: flip
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "echo -e 'GET /actuator/health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' > /dev/tcp/127.0.0.1/8080 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    image: anguy491/flip-frontend:latest
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/healthz.json || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  pgdata: {}
  caddy_data: {}
  caddy_config: {}

