version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flip
      POSTGRES_USER: flip
      POSTGRES_PASSWORD: flip
    # For production, consider removing the port mapping to avoid exposing DB directly.
    ports:
      - "5432:5432"  # remove in prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flip -d flip"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flip
      SPRING_DATASOURCE_USERNAME: flip
      SPRING_DATASOURCE_PASSWORD: flip
      APP_JWT_SECRET: ${APP_JWT_SECRET:-dev-local-secret-change}
      JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    # No volumes: built assets baked into image
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/healthz.json || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata: {}

