version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flip
      POSTGRES_USER: flip
      POSTGRES_PASSWORD: flip
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
