server:
  port: 8080

spring:
  flyway:
    enabled: true
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/flip
    username: flip
    password: flip
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

app:
  jwt:
    secret: "1aa1b1e7-32d4-426b-80a6-7bcbb7d0fe83"
